name: Update Docker Image on Push to Main

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout/mengunduh kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Login ke Docker Hub menggunakan secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah 3: Build dan push image ke Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true    
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/deepfake_detection_backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script:
            # Langkah 4: pull image terbaru dari Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/deepfake_detection_backend:latest

            # Langkah 5: stop dan remove container lama
            docker stop deepfake_detection_backend || true
            docker rm deepfake_detection_backend || true

            # Langkah 6: run container baru dengan image terbaru
            docker run -d --name deepfake_detection_backend -p 8080:8000 ${{ secrets.DOCKERHUB_USERNAME }}/deepfake_detection_backend:latest
            
            # Langkah 7: hapus dangling images
            docker image prune -f
            
            echo "Deployment completed successfully!"