name: Update Docker Image on Push to Main

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout/mengunduh kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Login ke Docker Hub menggunakan secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah 3: Build dan push image ke Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/dockerfile
          push: true          
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/deepfake_detection_backend:latest